name: CI Pipeline with SonarCloud

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-and-analyze:
    runs-on: ubuntu-22.04
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Set up JDK 17 for Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build and test the application
      - name: Build and test with Maven
        run: mvn clean verify
        working-directory: simple-api

      # SonarCloud analysis
      - name: SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.projectKey=albiche_tp_devops -Dsonar.organization=albiche -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        working-directory: simple-api

  build-and-push-docker-image:
    needs: test-and-analyze
    runs-on: ubuntu-22.04
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Login to DockerHub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build backend image
      - name: Build backend image
        uses: docker/build-push-action@v3
        with:
          context: ./simple-api
          tags: ${{ secrets.DOCKER_USERNAME }}/backend:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      # Build database image
      - name: Build database image
        uses: docker/build-push-action@v3
        with:
          context: ./database
          tags: ${{ secrets.DOCKER_USERNAME }}/database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      # Build HTTP server image
      - name: Build HTTP server image
        uses: docker/build-push-action@v3
        with:
          context: ./http-server
          tags: ${{ secrets.DOCKER_USERNAME }}/http-server:latest
          push: ${{ github.ref == 'refs/heads/main' }}
